# Generated by Django 3.1 on 2020-09-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200908_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_related', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_related', to='ecommerce.product'),
        ),
    ]
