# Generated by Django 3.1 on 2020-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200909_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(null=True, upload_to='user'),
        ),
    ]
