# Generated by Django 3.1 on 2020-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20201027_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(null=True, upload_to='product'),
        ),
    ]
